### ISSUE TITLE
Works on my Samsung S9 Exynos, but stuck after the 1st Gnome-Software upgrade

### ISSUE THREAD

**Issue by lakano** [droidian/droidian#28]
Hi,
Thank you for this amazing project.
I've succeed to install it on my phone, installed from my Arch, but with a older version of fastboot ( weird error on flash "std::out_of_range" fixed with version 30.0.5-6877874 )

Then after ~30 seconds of 1st boot, got the lockscreen and all the Gnome onboarding process, I don't known if it's my phone or software but the auto-rotate screen was buggy, I had to put my phone in diagonal and to remove the rotate option to keep it in portrait mode. The WiFi detection didn't success in the onboarding screen, but I could do it after without problem.

Then Gnome Softwares propose me to reboot to upgrades 4 packages ( system, calls, gnome-software and parameters ). Then, the phone reboot, I saw the Samsung logo and then the Droidian logo, but then it's a black screen and nothing appear anymore, seems to be shutdown. I've tried a lot of boot without success.

Then I've tried to flash it again, to try a 2nd time, but I had the exact same problem.

**Comment by FakeShell** [comment]
it should be fixed now.

**Comment by lakano** [comment]
It's works, thank you for your reactivity and this amazing work ! :)

But I had a weird situation, I've refreshed the packages lists, 4 packages to install with a reboot requested, but an error happen.
Then I've retry, only 2 packages to install ( System and Guide tour ), and the update/reboot seems to works, the reboot succeed without problem, but when I come back in Gnome Softwares, I still see the 2 same packages, and without any network connections.

Can't go on internet but the WiFi works. From the terminal, the list of network devices is huge, 27 devices detected, it's may be normal, but there is a problem of route somewhere.

I'll try to find a way to fix it, if I can't I'll open a new dedicated issue for this.
For now, I close this issue ticket related to the Gnome Sofwares bug.
